name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget curl make gcc g++ bc bison flex \
            libssl-dev libncurses5-dev libncursesw5-dev \
            python3 unzip device-tree-compiler \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Download Clang toolchain
        run: |
          mkdir -p $HOME/toolchains
          cd $HOME/toolchains
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/67af9f576276f27363074c4388e2cf0963bab6df/clang-r563880b.tar.gz
          mkdir clang-r563880b
          tar -xf clang-r563880b.tar.gz -C clang-r563880b
          ls clang-r563880b/bin

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v3
        with:
          name: kernel-image
          path: build/Image
